//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Billings = new HashSet<Billing>();
            this.Patients = new HashSet<Patient>();
        }

        public int userId { get; set; }

        [Required(ErrorMessage = "Name can not be empty")]
        [RegularExpression("^([a-zA-Z]{3,} )([a-zA-z]{3,})$", ErrorMessage ="Name must contain all letters and atleast 4 characters")]
        public string full_name { get; set; }

        [Required(ErrorMessage = "Email can not be empty")]
        [RegularExpression("^[a-z]+\\.[a-z0-9]+@[a-z]+\\.[a-z]{2,3}",ErrorMessage ="Please Enter valid Email")]
        public string email { get; set; }

        [Required(ErrorMessage = "User Name can not be empty")]
        public string userName { get; set; }

        [Required(ErrorMessage = "You have not provided Password")]
        public string password_ { get; set; }


        [Required(ErrorMessage = "Re-enter Password")]
        [Compare("password_", ErrorMessage = "Password didn't match..!!!")]
        public string confirmPassword_ { get; set; }

        [Required(ErrorMessage = "Enter your Age")]
        public Nullable<int> age { get; set; }

        [Required(ErrorMessage = "Contact Number can not be empty")]
        [RegularExpression("^[0-9]{10}", ErrorMessage = "Please enter valid mobile number")]
        public string contact_number { get; set; }

        [Required(ErrorMessage = "Select your Gender")]
        public string gender { get; set; }

        public string specialization { get; set; }

        public Nullable<int> role_id { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual Role Role { get; set; }
    }
}
